language: php
php:
  - '7.1'

before_install:
- composer require phpunit/phpunit:6.5.* satooshi/php-coveralls:^2.0
- composer install --dev

script:
- ./vendor/bin/phpunit --configuration phpunit.xml

after_script:
- php vendor/bin/coveralls -v