language: php
php:
  - '7.0'

before_install:
- composer require phpunit/phpunit:6.5.* satooshi/php-coveralls:dev-master
- composer install --dev

script:
- ./vendor/bin/phpunit --configuration phpunit.xml

after_script:
- php vendor/bin/coveralls -v