plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor

javascript:

baseurl: /react-express

navigation: false

projects: true

title: ReactExpress
description: ReactPHP application router written in express.js style

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
